export const SAVE_DATA_AUTH = 'AUTHORIZATION/SAVE_DATA_AUTH';

export const START_SAGAS_AUTH_POST_REQUEST = 'AUTHORIZATION/START_SAGAS_AUTH_POST_REQUEST';

export const START_SAGAS_AUTH_GET_LOGIN_REQUEST = 'AUTHORIZATION/START_SAGAS_AUTH_GET_LOGIN_REQUEST';

export const SAVE_DATA_FROM_LOGIN_WINDOW = 'AUTHORIZATION/SAVE_DATA_FROM_LOGIN_WINDOW';

export const FLAG_LOGIN_CONFIRMED = 'AUTHORIZATION/FLAG_LOGIN_CONFIRMED';

export const FLAG_REPEAT_PASSWORD_AUTH = 'AUTHORIZATION/FLAG_REPEAT_PASSWORD_AUTH';

export const CHANGE_DATA_AUTH = 'AUTHORIZATION/CHANGE_DATA_AUTH';

export const START_SAGAS_AUTH_PUT_REQUEST = 'AUTHORIZATION/START_SAGAS_AUTH_PUT_REQUEST';

