export const CHANGE_SEARCH_KEY = 'VIEW_TYPE/CHANGE_SEARCH_KEY';

export const START_GET_REQUEST = 'VIEW_TYPE/START_SAGA_GET_REQUEST';

export const START_POST_REQUEST = 'VIEW_TYPE/START_SAGA_POST_REQUEST';

export const START_PUT_REQUEST = 'VIEW_TYPE/START_SAGA_PUT_REQUEST';

export const START_DELETE_REQUEST = 'VIEW_TYPE/START_SAGA_DELETE_REQUEST';

export const TYPE_REQUEST = 'VIEW_TYPE/SAVE_TYPE_REQUEST';

export const NAME_WINDOW = 'VIEW_TYPE/SAVE_NAME_WINDOW';

export const ADD_DATA_COMPARE = 'VIEW_TYPE/ADD_DATA_COMPARE_ARR';

export const SORTING_ARR_COMPARE = 'VIEW_TYPE/SORTING_ARR_COMPARE';

export const DELETE_DATA_COMPARE = 'VIEW_TYPE/DELETE_DATA_COMPARE_ARR';

export const CLEAR_ARR_COMPARE = 'VIEW_TYPE/CLEAR_ARR_COMPARE';

export const CHANGE_ADRESS_OPEN_TABLE = 'VIEW_TYPE/CHANGE_ADRESS_OPEN_TABLE_BASE_OR_COMPARE';

export const FLAG_OPEN_COMPARE_WINDOW = 'VIEW_TYPE/FLAG_OPEN_COMPARE_WINDOW';