export const CHANGE_SEARCH_KEY = 'USER/CHANGE_SEARCH_KEY';

export const START_GET_REQUEST = 'USER/START_SAGA_GET_REQUEST';

export const START_POST_REQUEST = 'USER/START_SAGA_POST_REQUEST';

export const START_PUT_REQUEST = 'USER/START_SAGA_PUT_REQUEST';

export const START_DELETE_REQUEST = 'USER/START_SAGA_DELETE_REQUEST';

export const TYPE_REQUEST = 'USER/SAVE_TYPE_REQUEST';

export const NAME_WINDOW = 'USER/SAVE_NAME_WINDOW';

export const ADD_DATA_COMPARE = 'USER/ADD_DATA_COMPARE_ARR';

export const SORTING_ARR_COMPARE = 'USER/SORTING_ARR_COMPARE';

export const DELETE_DATA_COMPARE = 'USER/DELETE_DATA_COMPARE_ARR';

export const CLEAR_ARR_COMPARE = 'USER/CLEAR_ARR_COMPARE';

export const CHANGE_ADRESS_OPEN_TABLE = 'USER/CHANGE_ADRESS_OPEN_TABLE_BASE_OR_COMPARE';

export const FLAG_OPEN_COMPARE_WINDOW = 'USER/FLAG_OPEN_COMPARE_WINDOW';