//export const GET_REQUEST = 'ELTYPE_CLASS/GET_REQUEST';

//export const POST_REQUEST = 'ELTYPE_CLASS/POST_REQUEST';

//export const PUT_REQUEST = 'ELTYPE_CLASS/PUT_REQUEST';

//export const DELETE_REQUEST = 'ELTYPE_CLASS/DELETE_REQUEST';

//export const SORTING_TABLE = 'ELTYPE_CLASS/SORTING_ALL_TABLE';

//export const CREATE_DATA = 'ELTYPE_CLASS/SAVE_CREATE_DATA';

export const START_GET_REQUEST = 'ELTYPE_CLASS/START_SAGA_GET_REQUEST';

export const START_POST_REQUEST = 'ELTYPE_CLASS/START_SAGA_POST_REQUEST';

export const START_PUT_REQUEST = 'ELTYPE_CLASS/START_SAGA_PUT_REQUEST';

export const START_DELETE_REQUEST = 'ELTYPE_CLASS/START_SAGA_DELETE_REQUEST';

export const TYPE_REQUEST = 'ELTYPE_CLASS/SAVE_TYPE_REQUEST';

export const NAME_WINDOW = 'ELTYPE_CLASS/SAVE_NAME_WINDOW';

export const CHANGE_SEARCH_KEY = 'ELTYPE_CLASS/CHANGE_SEARCH_KEY';


//export const SHOW_LOADER = 'ELTYPE_CLASS/STATUS_SHOW_LOADER';

//export const COUNTER_PAGES_TABLE = 'ELTYPE_CLASS/GET_COUNTER_PAGES_TABLE';

//export const COUNT_ROW_TABLE = 'ELTYPE_CLASS/CHANGE_INPUT_COUNT_ROW_TABLE';

//export const CHANGE_ACTIV_ARR_NUMBER_PAGES = 'ELTYPE_CLASS/CHANGE_ACTIV_ARR_NUMBER_PAGES_FOOTER_TABLE';

//export const GET_DATA_LIST_TABLE = 'ELTYPE_CLASS/GET_DATA_LIST_TABLE';

//export const SORTING_LIST_TABLE = 'ELTYPE_CLASS/SORTING_ONLY_LIST_TABLE';

//export const CHANGE_NUMBER_LIST_TABLE = 'ELTYPE_CLASS/CHANGE_NUMBER_LIST_TABLE';

export const ADD_DATA_COMPARE = 'ELTYPE_CLASS/ADD_DATA_COMPARE_ARR';

export const SORTING_ARR_COMPARE = 'ELTYPE_CLASS/SORTING_ARR_COMPARE';

export const DELETE_DATA_COMPARE = 'ELTYPE_CLASS/DELETE_DATA_COMPARE_ARR';

export const CLEAR_ARR_COMPARE = 'ELTYPE_CLASS/CLEAR_ARR_COMPARE';

export const CHANGE_ADRESS_OPEN_TABLE = 'ELTYPE_CLASS/CHANGE_ADRESS_OPEN_TABLE_BASE_OR_COMPARE';

export const FLAG_OPEN_COMPARE_WINDOW = 'ELTYPE_CLASS/FLAG_OPEN_COMPARE_WINDOW';

//export const FLAG_CONTEXT_MENU = 'ELTYPE_CLASS/FLAG_CONTEXT_MENU';

//export const FLAG_BUTTON_OPEN_INPUT = 'ELTYPE_CLASS/FLAG_BUTTON_OPEN_INPUT';
