export const GET_REQUEST = 'BASIS_REPORT/GET_REQUEST';

export const POST_REQUEST = 'BASIS_REPORT/POST_REQUEST';

export const PUT_REQUEST = 'BASIS_REPORT/PUT_REQUEST';

export const DELETE_REQUEST = 'BASIS_REPORT/DELETE_REQUEST';

export const SORTING_TABLE = 'BASIS_REPORT/SORTING_ALL_TABLE';

export const CREATE_DATA = 'BASIS_REPORT/SAVE_CREATE_DATA';

export const START_FOCUS_DATA = 'BASIS_REPORT/START_FOCUS_DATA';

export const TYPE_REQUEST = 'BASIS_REPORT/SAVE_TYPE_REQUEST';

export const NAME_WINDOW = 'BASIS_REPORT/SAVE_NAME_WINDOW';

export const SHOW_LOADER = 'BASIS_REPORT/STATUS_SHOW_LOADER';

export const COUNTER_PAGES_TABLE = 'BASIS_REPORT/GET_COUNTER_PAGES_TABLE';

export const COUNT_ROW_TABLE = 'BASIS_REPORT/CHANGE_INPUT_COUNT_ROW_TABLE';

export const CHANGE_ACTIV_ARR_NUMBER_PAGES = 'BASIS_REPORT/CHANGE_ACTIV_ARR_NUMBER_PAGES_FOOTER_TABLE';

export const GET_DATA_LIST_TABLE = 'BASIS_REPORT/GET_DATA_LIST_TABLE';

export const SORTING_LIST_TABLE = 'BASIS_REPORT/SORTING_ONLY_LIST_TABLE';

export const CHANGE_NUMBER_LIST_TABLE = 'BASIS_REPORT/CHANGE_NUMBER_LIST_TABLE';

//export const ADD_DATA_COMPARE = 'ELTYPE_CLASS/ADD_DATA_COMPARE_ARR';

//export const SORTING_ARR_COMPARE = 'ELTYPE_CLASS/SORTING_ARR_COMPARE';

//export const DELETE_DATA_COMPARE = 'ELTYPE_CLASS/DELETE_DATA_COMPARE_ARR';

//export const CLEAR_ARR_COMPARE = 'ELTYPE_CLASS/CLEAR_ARR_COMPARE';

//export const CHANGE_ADRESS_OPEN_TABLE = 'ELTYPE_CLASS/CHANGE_ADRESS_OPEN_TABLE_BASE_OR_COMPARE';

export const FLAG_CONTEXT_MENU = 'BASIS_REPORT/FLAG_CONTEXT_MENU';

export const FLAG_BUTTON_OPEN_INPUT = 'BASIS_REPORT/FLAG_BUTTON_OPEN_INPUT';

